# Default configuration for Claude Code Guardian
# This file contains built-in rules that ship with the package

default_rules: true

rules:
  performance.grep_suggestion:
    type: pre_use_bash
    pattern: "^grep\\b(?!.*\\|)"
    action: deny
    message: "Use 'rg' (ripgrep) instead of 'grep' for better performance and features"
    priority: 50
    enabled: true

  performance.find_suggestion:
    type: pre_use_bash
    pattern: "^find\\s+\\S+\\s+-name\\b"
    action: deny
    message: "Use 'rg --files | rg pattern' or 'rg --files -g pattern' instead of 'find -name' for better performance"
    priority: 50
    enabled: true

  security.git_access:
    type: path_access
    scope: write
    action: deny
    message: "Direct access to .git directory is restricted for security"
    priority: 50
    paths:
      - pattern: "**/.git"
      - pattern: "**/.git/**"
    enabled: true
